<?php
// Plugin definition
$plugin = array(
  'title' => t('o2opz index'),
  'icon' => 'radix-bryant-flipped.png',
  'category' => t('o2opz'),
  'theme' => 'o2opz_index',
  'regions' => array(
    'sidebar' => t('Sidebar'),
    'contentfirstleft' => t('Content first left'),
    'contentfirstright' => t('Content first right'),
    'contentmain' => t('Content'),
    'bottom' => t('Bottom'),
  ),
);
