<?php
// Plugin definition
$plugin = array(
  'title' => t('jufeng index'),
  'icon' => 'radix-bryant-flipped.png',
  'category' => t('jufeng'),
  'theme' => 'jufeng_index',
  'regions' => array(
    'section1' => t('Section 1'),
    'section2_1' => t('Section 2-1'),
    'section2_2' => t('Section 2-2'),
    'section3_1' => t('Section 3-1'),
    'section3_2' => t('Section 3-2'),
    'section4_1' => t('Section 4-1'),
    'section4_2' => t('Section 4-2'),
  ),
);
